env:
  - dev:
      db_type: sqlite
      db_path: 'C:/Work/GitHub/db-autotest/Docs/m_sqlite.db'

metadata_db: 'C:/Work/GitHub/db-autotest/Docs/m_sqlite.db'

tables_module: 'C:/Work/GitHub/db-autotest/Python/src/m_lib/m_table/m_table.py'
rows_module: 'C:/Work/GitHub/db-autotest/Python/src/m_lib/m_table/m_row.py'

main_env:
  name: dev

fetch_child_rows: 1000
